.catalog:
  name: "Mautic"# Name of the versioned template of the Catalog Entry
  version: "v0.1-jackson"# Version of the versioned template of the Catalog Entry
  description: "Marketing tool"# Description of the versioned template of the Catalog Entry
  uuid: "mautic-0"# Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: "v.51.0"# The minimum version of Rancher that supports the template
  questions:    
   - variable: public_port
     description: "public port to access the wordpress site"
     label: "Public Port"
     required: true
     default: "80"
     type: "int"


wordpress:
